name: learning_app
description: A Korean learning Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  shared_preferences: ^2.2.3 # ë¡œê·¸ì¸ í† í° ì €ìž¥ì„ ìœ„í•œ íŒ¨í‚¤ì§€
  provider: ^6.1.2           # (ì„ íƒì‚¬í•­) ë” ë‚˜ì€ ìƒíƒœê´€ë¦¬ë¥¼ ìœ„í•´ ì¶”ì²œ
  translator: ^1.0.3+1
  table_calendar: ^3.2.0
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.1 # ë§ˆì´í¬, ì €ìž¥ì†Œ ë“± ê¶Œí•œ ê´€ë¦¬
  path_provider: ^2.1.3      # ì•±ì˜ íŒŒì¼ ì‹œìŠ¤í…œ ê²½ë¡œ ì ‘ê·¼
  audioplayers: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  flutter_tts: ^4.2.3
  timeago: ^3.7.1
  url_launcher: ^6.2.6
  app_links: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/fox.png
    - assets/all.png
    - assets/owl.png
    - assets/cat.png
    - assets/bear.png
    - assets/vocabulary.png
    - assets/conversation.png
    - assets/study.png
    - assets/community.png
    - assets/bookmark.png
    - assets/airport.png
    - assets/restaurant.png
    - assets/road.png
    - assets/hotel.png
    - assets/words_alpha.txt
    - assets/TOEIC:TOEFL.txt
    - assets/tatoeba_eng_50k.txt
    - assets/google.png
    - assets/kakao.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/all.png" # ðŸ‘ˆ 1ë‹¨ê³„ì—ì„œ ì¤€ë¹„í•œ ì•„ì´ì½˜ ì´ë¯¸ì§€ ê²½ë¡œ
  min_sdk_android: 21 # ì•ˆë“œë¡œì´ë“œ ìµœì†Œ SDK ë²„ì „ (ë³´í†µ 21)